/* Generated by AWAG */
import { Component } from '@angular/core';

import { ContactManagecontactComponent } from './contact-managecontact.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Contact (コンタクト履歴登録)
 * 画面：Managecontact (お客様コンタクト一覧)
 * @extends {ContactManagecontactComponent}
 */
@Component({
  selector: 'app-contact-managecontact',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './contact-managecontact.component.html',
  providers: ContactManagecontactComponent.providers
})
export class ContactManagecontactCustomComponent extends ContactManagecontactComponent {

  /**
   * @description
   * Custom logic for add (コンタクト履歴追加)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override addCustomLogic(model: any) {
    // customize logic here
    let max = 0;
    let num = 0;
    if (this.awagContext.getVModel('contact_managecontact').contacts) {
      for (const contact of this.awagContext.getVModel('contact_managecontact').contacts) {
        num = Number(contact.contactid);
        if (num > max) {
          max = num;
        }
      }
    }
    return { customerid: model.customerid, contactid: max + 1 };
  }

  /**
   * @description
   * Pre API call logic for contactsContactid (履歴番号)
   * @param {*} model Model data of screen
   * @param {number} index Index of selected row
   * @param {*} item Model data of selected item
   * @returns Edited model data of selected item
   *
  protected override contactsContactidPreCallLogic(model: any, index: number, item: any) {
    // customize logic here
    return item;
  }*/

  /**
   * @description
   * API success custom logic for contactsContactid (履歴番号)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override contactsContactidSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for contactsContactid (履歴番号)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override contactsContactidErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/
}
