/* Generated by AWAG */
import { Injectable } from '@angular/core';

import { MaintenanceSearchAwagSelectService } from './maintenance-search-awagselect.service';

/**
 * @description
 * API call service
 * 画面：Search (顧客検索（個人）)
 * イベント：AwagSelect (選択)
 * @extends {MaintenanceSearchAwagSelectService}
 */
@Injectable()
export class MaintenanceSearchAwagSelectCustomService extends MaintenanceSearchAwagSelectService {

  /**
   * @description
   * Execute API call.
   * @param {*} param API parameter
   * @returns {Observable<any>} Observable HTTP call
   *
  override execute(param: any): Observable<any> {
    return super.execute(param);
  }*/

}
