/* Generated by AWAG */
import { Injectable } from '@angular/core';
import { HttpEvent, HttpInterceptor, HttpHandler, HttpRequest } from '@angular/common/http';
import { Observable } from 'rxjs';

import { AwagLoggerService } from '../logger/awag-logger.service';
import { AwagLanguageSupportService } from './awag-language-support.service';

/**
 * @description
 * The AwagAuthInterceptor is HTTPInterceptor that provides JWT handling( get/add ) on each http requests.
 * @implements {HttpInterceptor}
 */
@Injectable({
  providedIn: 'root'
})
export class AwagLanguageSupportInterceptor implements HttpInterceptor {

  /**
   * @constructor
   * @param {AwagLoggerService} awagLogger
   * @param {AwagLanguageSupportService} awagLanguageSupport
   */
  constructor(
    protected awagLogger: AwagLoggerService,
    protected awagLanguageSupport: AwagLanguageSupportService,
  ) { }

  /**
   * @description
   * Intercept each http call and set Accept-Language.
   * @param {HttpRequest<any>} req
   * @param {HttpHandler} next
   * @returns {Observable<HttpEvent<any>>}
   */
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    this.awagLogger.develop('AwagLanguageSupportInterceptor.intercept()');
    const currentLanguage = this.awagLanguageSupport.getCurrentLanguage();
    if (currentLanguage != null && currentLanguage !== 'null') {
      req = req.clone({ withCredentials: true, headers: req.headers.set('Accept-Language', currentLanguage) });
    }
    return next.handle(req);
  }
}
