/* Generated by AWAG */
import { Component, OnInit } from '@angular/core';

import { AwagSharedModule } from '../awag/awag-shared.module';
import { AppCommonModule } from '../common/app-common.module';
import { HomeComponent } from './home.component';

/**
 * @description
 * Home custom component.
 * @extends {HomeComponent}
 * @implements {OnInit}
 */
@Component({
  selector: 'app-home',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './home.component.html',
  styleUrls: ['../common/app-common.scss', './home-custom.component.scss']
})
export class HomeCustomComponent extends HomeComponent implements OnInit {

  /**
   * @description
   * OnInit lifecycle hook.
   */
  override ngOnInit() {
    super.ngOnInit();
  }

}
