/* Generated by AWAG */
import { Component } from '@angular/core';

import { EmployeeAddComponent } from './employee-add.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Employee (社員情報メンテ)
 * 画面：Add (社員登録)
 * @extends {EmployeeAddComponent}
 */
@Component({
  selector: 'app-employee-add',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './employee-add.component.html',
  providers: EmployeeAddComponent.providers
})
export class EmployeeAddCustomComponent extends EmployeeAddComponent {

  /**
   * @description
   * Custom logic for confirm (登録確認)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override confirmCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagGoback (検索へ戻る)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagGobackCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagInit (初期処理)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override awagInitCustomLogic(model: any) {
    // customize logic here
    this.enrollmentStatusOptsCode.shift();
    return model;
  }
}
