/* Generated by AWAG */

/* eslint-disable @typescript-eslint/no-namespace */
/**
 * @description
 * アプリケーションで使用する各種定数をまとめた名前空間
 */
export namespace AppConstants {

  /**
   * @description ContactTypeOpt
   */
  export enum ContactTypeOpt {
    // 通常
    VALUE_1 = '1',
    // トラブル
    VALUE_2 = '2',
    // クレーム
    VALUE_3 = '3',
    // 意見・要望
    VALUE_4 = '4',
    // 賞賛
    VALUE_5 = '5',
  }

  /**
   * @description ProcessOpt
   */
  export enum ProcessOpt {
    // 問合せ
    VALUE_1 = '1',
    // 照会
    VALUE_2 = '2',
    // 受付
    VALUE_3 = '3',
    // 変更
    VALUE_4 = '4',
    // 取消
    VALUE_5 = '5',
    // 勧誘
    VALUE_6 = '6',
    // 確認
    VALUE_7 = '7',
    // 通知
    VALUE_8 = '8',
  }

  /**
   * @description chanelOpt
   */
  export enum ChanelOpt {
    // 電話受電
    VALUE_1 = '1',
    // IVR
    VALUE_2 = '2',
    // Web
    VALUE_3 = '3',
    // 郵送
    VALUE_4 = '4',
    // FAX
    VALUE_5 = '5',
    // E-mail
    VALUE_6 = '6',
    // 他ｸﾞﾙｰﾌﾟ
    VALUE_7 = '7',
    // その他
    VALUE_8 = '8',
  }

  /**
   * @description areaCheck
   */
  export enum AreaCheck {
    // 地区OFF
    VALUE_0 = '0',
    // 地区
    VALUE_1 = '1',
  }

  /**
   * @description areaOpts
   */
  export enum AreaOpts {
    // 北海道
    VALUE_0 = '0',
    // 東北
    VALUE_1 = '1',
    // 関東
    VALUE_2 = '2',
    // 中部
    VALUE_3 = '3',
    // 近畿
    VALUE_4 = '4',
    // 中国
    VALUE_5 = '5',
    // 四国
    VALUE_6 = '6',
    // 九州
    VALUE_7 = '7',
    // 沖縄
    VALUE_8 = '8',
  }

  /**
   * @description callnameselect1
   */
  export enum Callnameselect1 {
    // 選択１
    VALUE_0 = '0',
    // 選択２
    VALUE_1 = '1',
  }

  /**
   * @description callnameselect2
   */
  export enum Callnameselect2 {
    // 選択１
    VALUE_0 = '0',
    // 選択２
    VALUE_1 = '1',
  }

  /**
   * @description customerClass
   */
  export enum CustomerClass {
    // 個人
    VALUE_0 = '0',
    // 法人
    VALUE_1 = '1',
    // 加盟店
    VALUE_2 = '2',
  }

  /**
   * @description informationTypeOpts
   */
  export enum InformationTypeOpts {
    // あいおい損保
    VALUE_0 = '0',
    // あいおい生保
    VALUE_1 = '1',
  }

  /**
   * @description provinceOpts
   */
  export enum ProvinceOpts {
    // 青森
    VALUE_0 = '0',
    // 岩手
    VALUE_1 = '1',
    // 宮城
    VALUE_2 = '2',
    // 秋田
    VALUE_3 = '3',
    // 山形
    VALUE_4 = '4',
    // 福島
    VALUE_5 = '5',
  }

  /**
   * @description searchOpts
   */
  export enum SearchOpts {
    // 完全一致
    FULLMATCH = '0',
    // 前方一致
    APART_MATCH = '1',
  }

  /**
   * @description searchPaterns
   */
  export enum SearchPaterns {
    // カード会員番号
    VALUE_0 = '0',
    // 割賦契約番号
    VALUE_1 = '1',
    // 保険証券番号&情報種別
    VALUE_2 = '2',
    // 登録番号
    VALUE_3 = '3',
    // 顧客名(カナ)&顧客名(漢字)&生年月日&自宅電話番号
    VALUE_4 = '4',
    // 顧客名(カナ)&生年月日&自宅電話番号
    VALUE_5 = '5',
    // 顧客名(漢字)&生年月日&自宅電話番号
    VALUE_6 = '6',
    // 顧客名(ローマ字)&生年月日&自宅電話番号
    VALUE_7 = '7',
    // 顧客名(カナ)&顧客名(漢字)&生月日&自宅電話番号
    VALUE_8 = '8',
    // 顧客名(カナ)&生月日&自宅電話番号
    VALUE_9 = '9',
    // 顧客名(漢字)&生月日&自宅電話番号
    VALUE_10 = '10',
    // 顧客名(ローマ字)&生月日&自宅電話番号
    VALUE_11 = '11',
    // 顧客名(カナ)&顧客名(漢字)&自宅電話番号
    VALUE_12 = '12',
    // 顧客名(カナ)&自宅電話番号
    VALUE_13 = '13',
    // 顧客名(漢字)&自宅電話番号
    VALUE_14 = '14',
    // 顧客名(ローマ字)&自宅電話番号
    VALUE_15 = '15',
    // 自宅電話番号&生年月日
    VALUE_16 = '16',
    // 生月日&自宅電話番号
    VALUE_17 = '17',
    // 顧客名（カナ）&顧客名(漢字)&生年月日
    VALUE_18 = '18',
    // 顧客名(カナ)&生年月日
    VALUE_19 = '19',
    // 顧客名(漢字)&生年月日
    VALUE_20 = '20',
    // 顧客名(ローマ字)&生年月日
    VALUE_21 = '21',
    // 顧客名(ｶﾅ)&顧客名(漢字)&生月日
    VALUE_22 = '22',
    // 顧客名(カナ)&生月日
    VALUE_23 = '23',
    // 顧客名(漢字)&生月日
    VALUE_24 = '24',
    // 顧客名（ローマ字）&生月日
    VALUE_25 = '25',
    // 自宅電話番号
    VALUE_26 = '26',
    // 顧客名(カナ)
    VALUE_27 = '27',
    // 顧客名(漢字)
    VALUE_28 = '28',
    // 顧客名(ローマ字)
    VALUE_29 = '29',
    // 提携番号
    VALUE_30 = '30',
    // 顧客番号
    VALUE_31 = '31',
  }

  /**
   * @description transportdeptOpts
   */
  export enum TransportdeptOpts {
    // 北海道
    VALUE_北海道 = '北海道',
    // 東北
    VALUE_東北 = '東北',
    // 関東
    VALUE_関東 = '関東',
    // 中部
    VALUE_中部 = '中部',
    // 近畿
    VALUE_近畿 = '近畿',
  }

  /**
   * @description yearOpts
   */
  export enum YearOpts {
    // 昭和
    VALUE_0 = '0',
    // 平成
    VALUE_1 = '1',
    // 令和
    VALUE_2 = '2',
    // 大正
    VALUE_3 = '3',
    // 明治
    VALUE_4 = '4',
    // 西暦
    VALUE_5 = '5',
  }

}
/* eslint-enable @typescript-eslint/no-namespace */
