/* Generated by AWAG */
import { Component } from '@angular/core';
import { AppBase } from './app-base'
import { AwagSharedModule } from './awag/awag-shared.module';

@Component({
  selector: 'app-root',
  imports: [AwagSharedModule],
  templateUrl: './app.html',
  styleUrl: './app.scss'
})
export class App extends AppBase {
}