/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';


const appRoutes: Routes = [
  { path: 'land', loadComponent: () => import('./maintenance-land/maintenance-land-custom.component').then(m => m.MaintenanceLandCustomComponent) },
  { path: '', redirectTo: 'search', pathMatch: 'full' },
  { path: 'search', loadComponent: () => import('./maintenance-search/maintenance-search-custom.component').then(m => m.MaintenanceSearchCustomComponent) },
];

@NgModule({
  imports: [
    RouterModule.forChild(appRoutes),
  ]
})
export class MaintenanceModule { }
