/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';


const appRoutes: Routes = [
  { path: '', redirectTo: 'contactmaster', pathMatch: 'full' },
  { path: 'contactmaster', loadComponent: () => import('./contactmaster-contactmaster/contactmaster-contactmaster-custom.component').then(m => m.ContactmasterContactmasterCustomComponent) },
];

@NgModule({
  imports: [
    RouterModule.forChild(appRoutes),
  ]
})
export class ContactmasterModule { }
