/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { AwagConfirmModalComponent } from './awag-confirm-modal.component';

@NgModule({
  imports: [
    AwagConfirmModalComponent,
  ],
  exports: [
    AwagConfirmModalComponent,
  ]
})
export class AwagConfirmModalModule { }
