/* Generated by AWAG */
import { AfterViewInit, Component, ElementRef } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { AwagLoggerService } from '../logger/awag-logger.service';
import { AwagContextService } from '../awag-context.service';
import { AwagStandardModule } from '../awag-standard.module';

/**
 * @description
 * AwagModalComponentは確認ダイアログを表すクラスです。
 */
@Component({
  selector: 'app-awag-confirm-modal',
  imports: [AwagStandardModule],
  templateUrl: 'awag-confirm-modal.component.html'
})
export class AwagConfirmModalComponent implements AfterViewInit {

  /**
   * @constructor
   * @param {NgbActiveModal} modal
   * @param {AwagContextService} awagContext
   * @param {AwagLoggerService} awagLogger
   */
  constructor(
    protected el: ElementRef,
    protected modal: NgbActiveModal,
    protected awagContext: AwagContextService,
    protected awagLogger: AwagLoggerService,
  ) { }

  ngAfterViewInit() {
    const focusableElements = this.el.nativeElement.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
    const lastElement = focusableElements[focusableElements.length - 1];
    lastElement.focus();
  }

  set model(model: { [key: string]: any }) {
    if (model) {
      if (model['title'] !== undefined) {
        this.title = model['title'];
      }
      if (model['titleLabel'] !== undefined) {
        this.titleLabel = model['titleLabel'];
      }
      if (model['body'] !== undefined) {
        this.body = model['body'];
      }
      if (model['showDismissButton'] !== undefined) {
        this.showDismissButton = model['showDismissButton'];
      }
      if (model['dismissButtonLabel'] !== undefined) {
        this.dismissButtonLabel = model['dismissButtonLabel'];
      }
      if (model['showCloseButton'] !== undefined) {
        this.showCloseButton = model['showCloseButton'];
      }
      if (model['closeButtonLabel'] !== undefined) {
        this.closeButtonLabel = model['closeButtonLabel'];
      }
    }
  }

  /**
    * 確認ダイアログのタイトル文字列
    */
  title = null;

  /**
    * 確認ダイアログのタイトルラベル文字列
    */
  titleLabel = null;

  /**
   * 確認ダイアログのBody文字列
   */
  body = 'awag.label.sc.confirmmodal.body';

  /**
   * trueの場合、dismissボタンが表示されます。
   */
  showDismissButton = true;

  /**
   * dismissボタンのラベル
   */
  dismissButtonLabel = 'awag.label.sc.confirmmodal.dismissbutton';

  /**
   * trueの場合、closeボタンが表示されます。
   */
  showCloseButton = true;

  /**
   * closeボタンのラベル
   */
  closeButtonLabel = 'awag.label.sc.confirmmodal.closebutton';

  /**
   * モーダル領域外がクリックされたことを判定して処理します。
   * @param event Event
   */
  public clickElsewhere(event: Event) {
    if ((event.target as HTMLElement)?.classList.contains('awag-app-modal')) {
      (document.querySelector('.modal') as HTMLElement).click();
    }
  }

}
