/* Generated by AWAG */
/**
 * @description
 * The AwagAlert represents one alert.
 */
export class AwagAlert {

  /**
   * Alert code.
   */
  private _code: string;

  /**
   * Alert message.
   */
  private _message: string;

  /**
   * Alert display style(color, icon)
   */
  private _style: string;

  /**
   * @constructor
   * @param {string} code
   * @param {string} message
   * @param {string} [style='error'] display style of the alert.
   */
  constructor(code: string, message: string, style = 'error') {
    this._code = code;
    this._message = message;
    this._style = style;
  }

  /**
   * @description
   * Getter of code.
   * @returns {string} code
   */
  get code(): string {
    return this._code;
  }

  /**
   * @description
   * Setter of code.
   * @param {string} code
   */
  set code(code: string) {
    this._code = code;
  }

  /**
   * @description
   * Getter of message.
   * @returns {string} message
   */
  get message(): string {
    return this._message;
  }

  /**
   * @description
   * Setter of message.
   * @param {string} message
   */
  set message(message: string) {
    this._message = message;
  }

  /**
   * @description
   * Getter of style.
   * @returns {string} style
   */
  get style(): string {
    return this._style;
  }

  /**
   * @description
   * Setter of style.
   * @param {string} style
   */
  set style(style: string) {
    this._style = style;
  }
}
