/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { AwagAlertComponent } from './awag-alert.component';

@NgModule({
  imports: [
    AwagAlertComponent,
  ],
  exports: [
    AwagAlertComponent,
  ]
})
export class AwagAlertModule { }
