/* Generated by AWAG */
import { Component } from '@angular/core';

import { EmployeeAddconfirmComponent } from './employee-addconfirm.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Employee (社員情報メンテ)
 * 画面：Addconfirm (社員登録確認)
 * @extends {EmployeeAddconfirmComponent}
 */
@Component({
  selector: 'app-employee-addconfirm',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './employee-addconfirm.component.html',
  providers: EmployeeAddconfirmComponent.providers
})
export class EmployeeAddconfirmCustomComponent extends EmployeeAddconfirmComponent {

  /**
   * @description
   * Pre API call logic for add (登録)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override addPreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for add (登録)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override addSuccessCustomLogic(res: any) {
    // customize logic here
    return this.model;
  }/

  /**
   * @description
   * API error custom logic for add (登録)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override addErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagGoback (戻る)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagGobackCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for checkExists (存在チェック)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override checkExistsPreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for checkExists (存在チェック)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   */
  protected override checkExistsSuccessCustomLogic(res: any) {
    // customize logic here
    if (res.result == 'true') {
      this.showError('E004', '対象の社員番号は登録済みです。他の社員番号を指定してください。');
    } else {
      this.awagAlert.pushAlert('I004', '対象の社員番号は登録されていません。登録可能です。', 'info');
    }
    this.awagContext.setNextUrl(null);
    this.awagCommon.scrollToTop();
    return this.model;
  }

  /**
   * @description
   * API error custom logic for checkExists (存在チェック)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override checkExistsErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/
}
