/* Generated by AWAG */
import { Inject, Injectable } from '@angular/core';

import { ENVIRONMENT } from './awag-shared.module';
import { AWAG_LOGGER_LOGLEVEL } from './logger/awag-logger-loglevel';

/**
 * AwagEnvironmentService クラス
 * 
 * このクラスは Angular の環境設定サービスを定義します。
 * サービスはアプリケーション全体で提供され、API のベース URL やログレベルの設定情報を保持します。
 */
@Injectable({
  providedIn: 'root'
})
export class AwagEnvironmentService {

  /**
   * API のベース URL を保持するプロパティ
   */
  apiBaseUrl = '';

  /**
   * ログレベルを保持するプロパティ
   */
  logLevel: AWAG_LOGGER_LOGLEVEL = AWAG_LOGGER_LOGLEVEL.INFO;

  /**
   * コンストラクタ
   * ENVIRONMENT を注入して環境設定を取得します。
   * @param {any} environment - 注入された環境設定。
   */
  constructor(
    @Inject(ENVIRONMENT) private readonly environment: any
  ) {
    this.apiBaseUrl = environment.apiBaseUrl;
    this.logLevel = environment.logLevel;
  }

}