/* Generated by AWAG */
import { Injectable } from '@angular/core';

/**
 * @enum {number} VisibilityState
 * @description
 * UI要素の可視性と活動状態を表すための列挙型（enum）です。
 *
 * - `Active`: 活性表示
 * - `Inactive`: 非活性表示
 * - `Hidden`: 非表示
 * - `Undefined`: 定義されていない
 */
export enum AwagVisibilityState {
  Active = 2,
  Inactive = 1,
  Hidden = 0,
  Undefined = -1,
}
/**
 * @description
 * ロール別の画面項目表示制御設定
 * 画面の項目をロール別に活性表示・非活性表示・非表示制御を行うための設定です。
 */
export interface AwagRoleBasedVisibilityConfig {
  [sectionName: string]: {
    [itemId: string]: {
      [role: string]: AwagVisibilityState;
    }
  }
}
/**
 * @description
 * 画面項目表示制御設定
 */
export interface AwagVisibilityConfig {
  [sectionName: string]: {
    [itemId: string]: AwagVisibilityState;
  };
}
/**
 * @description
 * 確認対象要素毎のHiddenとInactive状態を保持するデータ型です。
 */
export interface AwagVisibility {
  sectionName: string,
  itemId: string,
  hidden: boolean;
  inactive: boolean;
}
/**
 * @description
 * ロール別の画面項目の表示制御を行う機能を提供するサービスクラスです。
 */
@Injectable({
  providedIn: 'root'
})
export class AwagVisibilityService {

  /**
   * @description
   * 定義されている画面項目に対して、保有するロールで最も優先度が高い表示制御を示す設定情報を取得します。
   * @param roleBasedVisibility ロール別の画面項目表示制御設定
   * @param userRoles ユーザーロール
   * @returns 画面項目表示制御設定
   */
  public getVisibilityConfig(roleBasedVisibility: AwagRoleBasedVisibilityConfig, userRoles: string[]): AwagVisibilityConfig {
    const visibilityConfig = {} as AwagVisibilityConfig;
    for (const sectionName in roleBasedVisibility) {
      visibilityConfig[sectionName] = {};
      for (const itemId in roleBasedVisibility[sectionName]) {
        let itemState = AwagVisibilityState.Undefined;
        // 保有ロールのうち最も高い状態を適用（Active > Inactive > Hidden）
        for (const userRole of userRoles) {
          const state = roleBasedVisibility[sectionName][itemId][userRole];
          if (state !== undefined) {
            itemState = Math.max(itemState, state);
          }
          visibilityConfig[sectionName][itemId] = itemState;
        }
      }
    }
    return visibilityConfig;
  }

}