/* Generated by AWAG */
import { Routes } from '@angular/router';
import { AppGuard } from './app.guard';

export const routes: Routes = [
  { path: '', redirectTo: '/home', pathMatch: 'full' },
  { path: 'home', loadChildren: () => import('./home/home.module').then(m => m.HomeModule), canDeactivate: [ AppGuard ] },
  { path: 'basicattributes', loadChildren: () => import('./basicattributes/basicattributes.module').then(m => m.BasicattributesModule), canDeactivate: [ AppGuard ] },
  { path: 'contacthistory', loadChildren: () => import('./contacthistory/contacthistory.module').then(m => m.ContactHistoryModule), canDeactivate: [ AppGuard ] },
  { path: 'maintenance', loadChildren: () => import('./maintenance/maintenance.module').then(m => m.MaintenanceModule), canDeactivate: [ AppGuard ] },
  { path: 'customecharacteristic', loadChildren: () => import('./customecharacteristic/customecharacteristic.module').then(m => m.CustomecharacteristicModule), canDeactivate: [ AppGuard ] },
  { path: 'contactmaster', loadChildren: () => import('./contactmaster/contactmaster.module').then(m => m.ContactmasterModule), canDeactivate: [ AppGuard ] },
  { path: 'creditcode', loadChildren: () => import('./creditcode/creditcode.module').then(m => m.CreditcodeModule), canDeactivate: [ AppGuard ] },
  { path: '**', redirectTo: '/home' }
];
