/* Generated by AWAG */
import { Component } from '@angular/core';

import { EmployeeSearchComponent } from './employee-search.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { AWAG_COMMON_MESSAGES } from '../../awag/awag-common-messages';
import { AwagError } from '../../awag/awag-error';

/**
 * @description
 * Screen custom component
 * メニュー：Employee (社員情報メンテ)
 * 画面：Search (社員検索)
 * @extends {EmployeeSearchComponent}
 */
@Component({
  selector: 'app-employee-search',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './employee-search.component.html',
  providers: EmployeeSearchComponent.providers
})
export class EmployeeSearchCustomComponent extends EmployeeSearchComponent {

  /**
   * @description
   * Pre API call logic for simpleSearch (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override simpleSearchPreCallLogic(model: any) {
    // customize logic here
    return {
      'employeeno': model.search.employeeno_tmp ?? '',
      'name': model.search.name_tmp ?? ''
    };
  }

  /**
   * @description
   * API success custom logic for simpleSearch (検索)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   */
  protected override simpleSearchSuccessCustomLogic(res: any) {
    // customize logic here
    if (res.body == null) {
      // 204 no content
      this.simpleSearchErrorLogic(new AwagError('204', AWAG_COMMON_MESSAGES['SCREEN_COMPONENT_AWAGSEARCH_204']), this.model);
      this.model.list = [];
    } else {
      this.model.list = res.body.list;
      if (res.body.awagMessage) {
        this.showMessage(res.body.awagMessage);
      }
    }
    return {
      body: this.model
    };
  }

  /**
   * @description
   * API error custom logic for simpleSearch (検索)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override simpleSearchErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for awagSearch (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagSearchPreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for awagSearch (検索)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override awagSearchSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for awagSearch (検索)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagSearchErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for add (追加)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override addCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for view (詳細表示)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override viewCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for awagSelect (選択)
   * @param {*} model Model data of screen
   * @param {number} index Index of selected row
   * @param {*} item Model data of selected item
   * @returns Edited model data of selected item
   *
  protected override awagSelectPreCallLogic(model: any, index: number, item: any) {
    // customize logic here
    return item;
  }*/

  /**
   * @description
   * API success custom logic for awagSelect (選択)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override awagSelectSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for awagSelect (選択)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagSelectErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for update (更新)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override updateCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for delete (削除)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override deleteCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/
}
