/* Generated by AWAG */
import { Component } from '@angular/core';

import { ApproveGridinputComponent } from './approve-gridinput.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Approve (一括承認)
 * 画面：Gridinput (未承認一覧)
 * @extends {ApproveGridinputComponent}
 */
@Component({
  selector: 'app-approve-gridinput',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './approve-gridinput.component.html',
  providers: ApproveGridinputComponent.providers
})
export class ApproveGridinputCustomComponent extends ApproveGridinputComponent {

  /**
   * @description
   * Custom logic for awagGridConfirm (確認へ)
   * @param {*} model Model data of selected items in the grid table
   * @returns Edited model data
   *
  protected override awagGridConfirmCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for awagInit (初期処理)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override awagInitPreCallLogic(model: any) {
    // customize logic here
    return { checkbox: '100' };
  }

  /**
   * @description
   * API success custom logic for awagInit (初期処理)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   */
  protected override awagInitSuccessCustomLogic(res: any) {
    // customize logic here
    res.list.forEach((item: any) => {
      item.approvelog = item.approvelog ?? {};
    });
    return res;
  }

  /**
   * @description
   * API error custom logic for awagInit (初期処理)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagInitErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for awagSearch (再検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagSearchPreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for awagSearch (再検索)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   */
  protected override awagSearchSuccessCustomLogic(res: any) {
    return this.awagInitSuccessCustomLogic(res);
  }

  /**
   * @description
   * API error custom logic for awagSearch (再検索)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagSearchErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/
}
