/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';


const appRoutes: Routes = [
  { path: '', redirectTo: 'contracthistorylist', pathMatch: 'full' },
  { path: 'contracthistorylist', loadComponent: () => import('./contracthistorylist-contracthistorylist/contracthistorylist-contracthistorylist-custom.component').then(m => m.ContractHistoryListContractHistoryListCustomComponent) },
];

@NgModule({
  imports: [
    RouterModule.forChild(appRoutes),
  ]
})
export class ContractHistoryListModule { }
