/* Generated by AWAG */
import { AfterViewInit, Component, OnDestroy } from '@angular/core';

import { AwagAlertService } from './service/awag-alert.service';
import { AwagContextService } from '../awag-context.service';
import { AwagAlert } from './awag-alert';
import { AwagStandardModule } from '../awag-standard.module';

/**
 * @description
 * AwagAlertComponentはアラート（AWAGAlert）を表示するためのコンポーネントです。表示するアラートはAwagAlertServiceを使用してpushすることができます。
 */
@Component({
  selector: 'app-awag-alert',
  imports: [AwagStandardModule],
  templateUrl: 'awag-alert.component.html'
})
export class AwagAlertComponent implements AfterViewInit, OnDestroy {

  /**
   * モーダル状態
   */
  private isModal = false;

  /**
   * @constructor
   * @param awagAlert
   * @param awagContext
   */
  constructor(
    protected awagAlert: AwagAlertService,
    protected awagContext: AwagContextService,
  ) {
  }

  /**
   * @description
   * 画面初期化時にモーダル状態を確認します。
   */
  ngAfterViewInit() {
    this.isModal = (this.awagContext.getModalContext() != null);
  }

  /**
   * @description
   * 画面遷移時にアラートをクリアします。
   */
  ngOnDestroy(): void {
    this.awagAlert.clearAlerts();
  }

  /**
   * @description
   * モーダル状態を指定してアラート一覧を取得します。
   * @returns アラート一覧
   */
  getAlerts(): AwagAlert[] {
    return this.awagAlert.getAlerts(this.isModal);
  }

  /**
   * @description
   * AwagAlertServiceに保持しているアラートをクリアします。
   */
  closeNotification(index: number) {
    this.awagAlert.removeAlerts(index);
  }

}
