/* Generated by AWAG */
import { Component } from '@angular/core';

import { MaintenanceViewComponent } from './maintenance-view.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Maintenance (お客様情報メンテ)
 * 画面：View (詳細表示)
 * @extends {MaintenanceViewComponent}
 */
@Component({
  selector: 'app-maintenance-view',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './maintenance-view.component.html',
  providers: MaintenanceViewComponent.providers
})
export class MaintenanceViewCustomComponent extends MaintenanceViewComponent {

  /**
   * @description
   * Custom logic for awagGoback (検索へ戻る)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagGobackCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for attachments (添付ファイル一覧)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override attachmentsCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagInit (初期処理)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override awagInitCustomLogic(model: any) {
    // customize logic here
    // 画面初期化時にcustclass1の値に応じて選択肢class2Optsを書き換える
    if (this.model.custclass1) {
      const url = this.awagCommon.getEnvironment().apiBaseUrl + '/app/api/codemaster/search?category=' + this.model.custclass1 + '&language=' + this.awagLanguageSupport.getCurrentLanguage();
      this.appNameValue.loadNameValueFrom(url, this.class2OptsCode);
      const { custclass2 } = model;
      setTimeout(() => {
        this.model.custclass2 = custclass2;
      }, 250);
      model.custclass2 = null;
    } else {
      this.class2OptsCode.length = 0;
    }
    return model;
  }

}
