/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';


const appRoutes: Routes = [
  { path: '', loadComponent:() => import('./home-custom.component').then(m => m.HomeCustomComponent) },
];

@NgModule({
  imports: [
    RouterModule.forChild(appRoutes),
  ]
})
export class HomeModule { }
