/* Generated by AWAG */
import { Component } from '@angular/core';

import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { MaintenanceSearchComponent } from './maintenance-search.component';
import { AwagListController } from '../../awag/awag-listcontroller';

// liu-add 20250822 PRJ標準確認事項：ハイフン有無許容
import { FormsModule } from "@angular/forms";
// liu-add 20250825 PRJ標準確認事項：文字のツールチップ表示
import { MatTooltipModule } from "@angular/material/tooltip";
import { MatSnackBar } from "@angular/material/snack-bar";
import { ContactHistoryComponent } from "../../maintenance/contact-history/contact-history.component";

/**
 * @description
 * Screen custom component
 * メニュー：Maintenance (お客様情報メンテ)
 * 画面：Search (顧客検索（個人）)
 * @extends {MaintenanceSearchComponent}
 */
@Component({
  selector: 'app-maintenance-search',
  imports: [AppCommonModule, AwagSharedModule, FormsModule, MatTooltipModule],
  templateUrl: './maintenance-search.component.html',
  styleUrls: ['../../common/app-common.scss', './maintenance-search-custom.component.scss'],
  providers: MaintenanceSearchComponent.providers
})
export class MaintenanceSearchCustomComponent extends MaintenanceSearchComponent {

  /**
   * @description
   * Custom logic for sVClink (SVC連携)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override sVClinkCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for awagSearch (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagSearchPreCallLogic(model: any) {
    // customize logic here
    if (model.areaCheck != this.areaCheckCode[1].value) {
      // SEARCH_TABLE checkbox control, Change the condition when the checkbox is not checked, default : 'model.areaCheck = null';
      // model.areaCheck = this.areaCheckCode[0].value;
    }
    return model;
  }*/

  /**
   * @description
   * API success custom logic for awagSearch (検索)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override awagSearchSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for awagSearch (検索)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagSearchErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for landsearch (陸事検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override landsearchCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for clear (クリア)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override clearCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/
}
