/* Generated by AWAG */
import { Injectable } from '@angular/core';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

/**
 * @description
 * Commonサービスを提供するクラス。
 */
@Injectable({
  providedIn: 'root'
})
export class AppCommonService {

  /**
   * @constructor
   * @param {NgbModal} modal
   */
  constructor(
    protected modal: NgbModal
  ) {
  }

  /**
   * @description
   * モーダル画面オブジェクトを取得します。
   * @returns {NgbModal} モーダル画面オブジェクト
   */
  public getModal(): NgbModal {
    return this.modal;
  }
}