/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';


const appRoutes: Routes = [
  { path: '', redirectTo: 'contacthistory', pathMatch: 'full' },
  { path: 'contacthistory', loadComponent: () => import('./contacthistory-contacthistory/contacthistory-contacthistory-custom.component').then(m => m.ContactHistoryContactHistoryCustomComponent) },
];

@NgModule({
  imports: [
    RouterModule.forChild(appRoutes),
  ]
})
export class ContactHistoryModule { }
