/* Generated by AWAG */
import { Injectable } from '@angular/core';

import { MaintenanceSearchSearchService } from './maintenance-search-search.service';

/**
 * @description
 * API call service
 * 画面：Search (顧客検索（個人）)
 * イベント：Search (検索)
 * @extends {MaintenanceSearchSearchService}
 */
@Injectable()
export class MaintenanceSearchSearchCustomService extends MaintenanceSearchSearchService {

  /**
   * @description
   * Execute API call.
   * @param {*} param API parameter
   * @returns {Observable<any>} Observable HTTP call
   *
  override execute(param: any): Observable<any> {
    return super.execute(param);
  }*/

}
