/* Generated by AWAG */
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable } from 'rxjs';

import { AwagBaseService } from '../../../awag/awag-base.service';
import { AwagCommonService } from '../../../awag/awag-common.service';
import { AwagContextService } from '../../../awag/awag-context.service';
import { AwagLoggerService } from '../../../awag/logger/awag-logger.service';

/**
 * @description
 * API call service
 * 画面：Search (顧客検索)
 * イベント：AwagSearch (検索)
 * @extends {AwagBaseService}
 */
@Injectable()
export class MaintenanceSearchAwagSearchService extends AwagBaseService {

  /**
   * @constructor
   * @param {HttpClient} http
   * @param {AwagCommonService} awagCommon
   * @param {AwagContextService} awagContext
   * @param {AwagLoggerService} awagLogger
   */
  constructor(
    protected override http: HttpClient,
    protected override awagCommon: AwagCommonService,
    protected override awagContext: AwagContextService,
    protected override awagLogger: AwagLoggerService,
  ) {
    super(http, awagCommon, awagContext, awagLogger);
  }

  /**
   * @description
   * Execute API call.
   * @param {*} param API parameter
   * @returns {Observable<any>} Observable HTTP call
   */
  execute(param: any): Observable<any> {
    this.awagLogger.debug('MaintenanceSearchAwagSearchService.execute()');
    const apiUrl = super.getApiBaseUrl() + '/app/api/maintenance/search';
    return this.get(apiUrl, param);
  }
}
