/* Generated by AWAG */
import { Component } from '@angular/core';

import { MaintenanceUpdateComponent } from './maintenance-update.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Maintenance (お客様情報メンテ)
 * 画面：Update (更新)
 * @extends {MaintenanceUpdateComponent}
 */
@Component({
  selector: 'app-maintenance-update',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './maintenance-update.component.html',
  providers: MaintenanceUpdateComponent.providers
})
export class MaintenanceUpdateCustomComponent extends MaintenanceUpdateComponent {

  /**
   * @description
   * Custom logic for confirm (更新確認)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override confirmCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagGoback (検索へ戻る)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagGobackCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for houjinnoAwagAutoComplete (法人番号 awagAutoComplete)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override houjinnoAwagAutoCompletePreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for houjinnoAwagAutoComplete (法人番号 awagAutoComplete)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override houjinnoAwagAutoCompleteSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for houjinnoAwagAutoComplete (法人番号 awagAutoComplete)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override houjinnoAwagAutoCompleteErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagInit (初期処理)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override awagInitCustomLogic(model: any) {
    // customize logic here
    // 画面初期化時にcustclass1の値に応じて選択肢class2Optsを書き換える
    if (this.model.custclass1) {
      const url = this.awagCommon.getEnvironment().apiBaseUrl + '/app/api/codemaster/search?category=' + this.model.custclass1 + '&language=' + this.awagLanguageSupport.getCurrentLanguage();
      this.appNameValue.loadNameValueFrom(url, this.class2OptsCode);
      const { custclass2 } = model;
      setTimeout(() => {
        this.model.custclass2 = custclass2;
      }, 250);
      model.custclass2 = null;
    } else {
      this.class2OptsCode.length = 0;
    }
    return model;
  }

  /**
   * @description
   * Custom logic for custclass1onChange (お客様区分1 onChange)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override custclass1OnChangeCustomLogic(model: any) {
    if (model.custclass1) {
      const url = this.awagCommon.getEnvironment().apiBaseUrl + '/app/api/codemaster/search?category=' + model.custclass1 + '&language=' + this.awagLanguageSupport.getCurrentLanguage();
      this.appNameValue.loadNameValueFrom(url, this.class2OptsCode);
      const { custclass2 } = model;
      setTimeout(() => {
        this.model.custclass2 = custclass2;
      }, 250);
      model.custclass2 = null;
    } else {
      this.class2OptsCode.length = 0;
    }
    return this.model;
  }

}
