/* Generated by AWAG */
import { Component } from '@angular/core';

import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { ContactHistoryContactHistoryComponent } from './contacthistory-contacthistory.component';

/**
 * @description
 * Screen custom component
 * メニュー：ContactHistory (コンタクト履歴一覧)
 * 画面：Contacthistory (コンタクト履歴一覧)
 * @extends {ContactHistoryContacthistoryComponent}
 */
@Component({
  selector: 'app-contacthistory-contacthistory',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './contacthistory-contacthistory.component.html',
  styleUrls: ['../../common/app-common.scss', './contacthistory-contacthistory-custom.component.scss'],
  providers: ContactHistoryContactHistoryComponent.providers
})
export class ContactHistoryContactHistoryCustomComponent extends ContactHistoryContactHistoryComponent {

  /**
   * @description
   * Custom logic for awagSearch (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagSearchCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for detail (詳細)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override detailCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/
}
