/* Generated by AWAG */
import { Component } from '@angular/core';

import { InputcustomerConfirmComponent } from './inputcustomer-confirm.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { AwagError } from '../../awag/awag-error';

/**
 * @description
 * Screen custom component
 * メニュー：Inputcustomer (お客様登録)
 * 画面：Confirm (登録確認)
 * @extends {InputcustomerConfirmComponent}
 */
@Component({
  selector: 'app-inputcustomer-confirm',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './inputcustomer-confirm.component.html',
  providers: InputcustomerConfirmComponent.providers
})
export class InputcustomerConfirmCustomComponent extends InputcustomerConfirmComponent {

  /**
   * @description
   * Pre API call logic for confirm (登録)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override confirmPreCallLogic(model: any) {
    // customize logic here
    if (model.katakana?.startsWith('アイビーエム')) {
      let error = this.awagContext.getError();
      error ??= new AwagError();
      error.pushDetail('E999', 'このお客様名(カナ)は利用することができません。');
      this.awagContext.setError(error);
      this.awagContext.setNextUrl('/inputcustomer/input'); // input画面に遷移します。
      this.awagContext.setCancelApi(true); // API呼出をキャンセルします。
    } else {
      model.checkbox = '000';
      model.approvelog = { flag: model.checkbox };
    }
    return model;
  }

  protected override get confirmModalModel(): { [key: string]: any } {
    return {
      body: 'custom.prj.uc.inputcustomer.sc.confirm.fl.confirmmodal.body',
      showDismissButton: true,
      dismissButtonLabel: 'custom.prj.uc.inputcustomer.sc.confirm.fl.confirmmodal.dismissbutton',
      showCloseButton: true,
      closeButtonLabel: 'custom.prj.uc.inputcustomer.sc.confirm.fl.confirmmodal.closebutton'
    };
  }

  /**
   * @description
   * API success custom logic for confirm (登録)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override confirmSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for confirm (登録)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override confirmErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagGoback (入力へ戻る)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagGobackCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagInit (初期処理)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override awagInitCustomLogic(model: any) {
    // customize logic here
    // 画面初期化時にcustclass1の値に応じて選択肢class2Optsを書き換える
    if (this.model.custclass1) {
      const url = this.awagCommon.getEnvironment().apiBaseUrl + '/app/api/codemaster/search?category=' + this.model.custclass1 + '&language=' + this.awagLanguageSupport.getCurrentLanguage();
      this.appNameValue.loadNameValueFrom(url, this.class2OptsCode);
      const { custclass2 } = model;
      setTimeout(() => {
        this.model.custclass2 = custclass2;
      }, 250);
      model.custclass2 = null;
    } else {
      this.class2OptsCode.length = 0;
    }
    return model;
  }

}
