/* Generated by AWAG */
import { Component } from '@angular/core';

import { MaintenanceConfirmComponent } from './maintenance-confirm.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Maintenance (お客様情報メンテ)
 * 画面：Confirm (更新確認)
 * @extends {MaintenanceConfirmComponent}
 */
@Component({
  selector: 'app-maintenance-confirm',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './maintenance-confirm.component.html',
  providers: MaintenanceConfirmComponent.providers
})
export class MaintenanceConfirmCustomComponent extends MaintenanceConfirmComponent {

  /**
   * @description
   * Custom logic for awagGoback (入力へ戻る)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagGobackCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for awagInit (初期処理)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override awagInitCustomLogic(model: any) {
    // customize logic here
    // 画面初期化時にcustclass1の値に応じて選択肢class2Optsを書き換える
    if (this.model.custclass1) {
      const url = this.awagCommon.getEnvironment().apiBaseUrl + '/app/api/codemaster/search?category=' + this.model.custclass1 + '&language=' + this.awagLanguageSupport.getCurrentLanguage();
      this.appNameValue.loadNameValueFrom(url, this.class2OptsCode);
      const { custclass2 } = model;
      setTimeout(() => {
        this.model.custclass2 = custclass2;
      }, 250);
      model.custclass2 = null;
    } else {
      this.class2OptsCode.length = 0;
    }
    return model;
  }

  /**
   * @description
   * Pre API call logic for update (更新)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override updatePreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for update (更新)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override updateSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for update (更新)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override updateErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

}
