/* Generated by AWAG */
import { Component } from '@angular/core';

import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { ContactmasterContactmasterComponent } from './contactmaster-contactmaster.component';

/**
 * @description
 * Screen custom component
 * メニュー：Contactmaster (コンタクト履歴マスタ)
 * 画面：Contactmaster (コンタクト履歴マスタ管理)
 * @extends {ContactmasterContactmasterComponent}
 */
@Component({
  selector: 'app-contactmaster-contactmaster',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './contactmaster-contactmaster.component.html',
  styleUrls: ['../../common/app-common.scss', './contactmaster-contactmaster-custom.component.scss'],
  providers: ContactmasterContactmasterComponent.providers
})
export class ContactmasterContactmasterCustomComponent extends ContactmasterContactmasterComponent {

  /**
   * @description
   * Custom logic for serch1 (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override serch1CustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for serch2 (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override serch2CustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for serch3 (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override serch3CustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for serch4 (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override serch4CustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for serch5 (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override serch5CustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for change (変更)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override changeCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for registration (登録)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override registrationCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for delete (削除)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override deleteCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for close (閉じる)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override closeCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/
}
