/* Generated by AWAG */
// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.
import { AWAG_LOGGER_LOGLEVEL } from '../app/awag/logger/awag-logger-loglevel';

export const environment = {
  production: false,
  apiBaseUrl: '',
  logLevel: AWAG_LOGGER_LOGLEVEL.DEBUG
};
