/* Generated by AWAG */
import { Component } from '@angular/core';

import { ContactThanksComponent } from './contact-thanks.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Contact (コンタクト履歴登録)
 * 画面：Thanks (コンタクト更新完了)
 * @extends {ContactThanksComponent}
 */
@Component({
  selector: 'app-contact-thanks',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './contact-thanks.component.html',
  providers: ContactThanksComponent.providers
})
export class ContactThanksCustomComponent extends ContactThanksComponent {

  /**
   * @description
   * Pre API call logic for goback (コンタクト一覧に戻る)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override gobackPreCallLogic(model: any) {
    // customize logic here
    return { customerid: this.awagContext.getVModel('contact_managecontact').customerid };
  }

  /**
   * @description
   * API success custom logic for goback (コンタクト一覧に戻る)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override gobackSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for goback (コンタクト一覧に戻る)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override gobackErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/
}
