/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';


const appRoutes: Routes = [
  { path: '', redirectTo: 'customecharacteristic', pathMatch: 'full' },
  { path: 'customecharacteristic', loadComponent: () => import('./customecharacteristic-customecharacteristic/customecharacteristic-customecharacteristic-custom.component').then(m => m.CustomecharacteristicCustomecharacteristicCustomComponent) },
];

@NgModule({
  imports: [
    RouterModule.forChild(appRoutes),
  ]
})
export class CustomecharacteristicModule { }
