/* Generated by AWAG */

/**
 * @description
 * ユーザー情報
 */
export class AwagUser {

  /**
   * ログイン前のデフォルトユーザー
   */
  static readonly DEFAULT: AwagUser = new AwagUser('guest', 'Guest', ['guest'], false);

  /**
   * ユーザーID
   */
  private readonly _userId: string;

  /**
   * ユーザー名
   */
  private readonly _userName: string;

  /**
   * ユーザーロール
   */
  private readonly _userRoles: string[];

  /**
   * ログイン状態
   */
  private readonly _isLogin: boolean;

  /**
   * @constructor
   * @param userId ユーザーID
   * @param userName ユーザー名
   * @param userRoles ユーザーロール
   * @param [isLogin=true] ログイン状態
   */
  constructor(userId: string, userName: string, userRoles: string[], isLogin = true) {
    this._userId = userId;
    this._userName = userName;
    this._userRoles = userRoles;
    this._isLogin = isLogin;
  }

  /**
   * @description
   * ユーザーIDを取得します。
   * @returns ユーザーID
   */
  getUserId(): string {
    return this._userId;
  }

  /**
   * @description
   * ユーザー名を取得します。
   * @returns ユーザー名
   */
  getUserName(): string {
    return this._userName;
  }

  /**
   * @description
   * ユーザーロールを取得します。
   * @returns ユーザーロール
   */
  getUserRoles(): string[] {
    return this._userRoles;
  }

  /**
   * @description
   * ログイン状態を取得します。
   * @returns ログイン状態
   */
  isLogin(): boolean {
    return this._isLogin;
  }

}
