/* Generated by AWAG */

/**
 * @description
 * AwagSubContextはサブユースケース用のContextを表すクラスです。
 */
export class AwagSubContext {

  /**
   * SubContext ID
   */
  private readonly id: string = 'sc' + Date.now().toString();

  /**
   * サブユースケースからの戻り先パス
   */
  private returnToPath: string | null = null;

  /**
   * サブユースケースが完了した状態である場合
   */
  private returnState = false;

  /**
   * 呼び出し元の画面モデル取得キー
   */
  private baseModelKey: string = '';

  /**
   * マージが許可されたプロパティ
   */
  private allowedMergeProperties: string[] | null = null;

  /**
   * サブユースケース用のModelデータ
   */
  private nextModel: any = {};

  /**
   * SubContextのIDを返します。
   * @returns ID
   */
  getId(): string {
    return this.id;
  }

  /**
   * @description
   * サブユースケースからの戻り先パスを取得します。
   * @returns {string} サブユースケースからの戻り先パス
   */
  getReturnToPath(): string | null {
    return this.returnToPath;
  }

  /**
   * @description
   * サブユースケースからの戻り先パスを設定します。
   * @param {string} value サブユースケースからの戻り先パス
   */
  setReturnToPath(value: string) {
    this.returnToPath = value;
  }

  /**
   * サブユースケースが完了した状態であるかを確認します
   * @returns サブユースケースが完了した状態である
   */
  isReturn(): boolean {
    return this.returnState;
  }

  /**
   * サブユースケースが完了した状態を設定します
   * @param returnState サブユースケースが完了した状態である
   */
  setReturn(returnState: boolean) {
    this.returnState = returnState;
  }

  /**
   * @description
   * 呼び出し元の画面モデル取得キーを取得します。
   * @returns {any} 呼び出し元の画面モデル取得キー
   */
  getBaseModelKey(): string  {
    return this.baseModelKey;
  }

  /**
   * @description
   * 呼び出し元の画面モデル取得キーを設定します。
   * @param {any} model 呼び出し元の画面モデル取得キー
   */
  setBaseModelKey(baseModelKey: string) {
    this.baseModelKey = baseModelKey;
  }

  /**
   * @description
   * マージが許可されたプロパティを取得します。
   * @returns {any} マージが許可されたプロパティ
   */
  getAllowedMergeProperties(): string[] | null {
    return this.allowedMergeProperties;
  }

  /**
   * @description
   * マージが許可されたプロパティを設定します。
   * @param {any} model マージが許可されたプロパティ
   */
  setAllowedMergeProperties(allows: string[] | null) {
    this.allowedMergeProperties = allows;
  }

  /**
   * @description
   * サブユースケース用のModelデータを取得します。
   * @returns {*} サブユースケース用のModelデータ
   */
  getNextModel(): any {
    return this.nextModel;
  }

  /**
   * @description
   * サブユースケース用のModelデータを設定します。
   * modelに含まれるデータのタイプはプリミティブ型 (Boolean/Null/Number/String) または array型である必要があります。 他のデータ型のデータは欠落または削除される可能性があります。
   * @param {*} model サブユースケース用のModelデータ
   */
  setNextModel(model: any) {
    this.nextModel = JSON.parse(JSON.stringify(model));
  }

}
