/* Generated by AWAG */
import { InjectionToken, ModuleWithProviders, NgModule } from '@angular/core';

import { AwagAlertModule } from './alert/awag-alert.module';
import { AwagConfirmModalModule } from './modal/awag-confirm-modal.module';
import { AwagTranslateValidationMessagePipe } from './language-support/awag-translate-validation-message.pipe';
import { AwagBootstrapComponentsModule } from './awag-bootstrap-components';
import { AwagSharedDirectivesModule } from './awag-shared-directives';
import { AwagStandardModule } from './awag-standard.module';

export const ENVIRONMENT = new InjectionToken<any>('Environment');

@NgModule({
  imports: [
    AwagTranslateValidationMessagePipe
  ],
  exports: [
    AwagStandardModule,
    AwagAlertModule,
    AwagConfirmModalModule,
    AwagBootstrapComponentsModule,
    AwagSharedDirectivesModule,
    AwagTranslateValidationMessagePipe
  ]
})
export class AwagSharedModule {
  static forRoot(environment: any): ModuleWithProviders<AwagSharedModule> {
    return {
      ngModule: AwagSharedModule,
      providers: [
        {
          provide: ENVIRONMENT, useValue: environment
        }
      ]
    }
  }
}
