/* Generated by AWAG */
/**
 * @description
 * エラー情報を表すクラスです。エラーコード、エラーメッセージ、関連する詳細エラー（複数）を保持します。
 */
export class AwagError {
  /**
   * エラーコード
   */
  private _code?: string;

  /**
   * エラーメッセージ
   */
  private _message?: string;

  /**
   * 詳細エラー（クライアント）
   */
  private _details: AwagError[];

  /**
   * 詳細エラー（サーバエラー）
   */
  private _errors?: AwagError[];

  /**
   * @constructor
   * @param {(string | number)} [code] Error code
   * @param {string} [message] Error message
   * @param {*} [details=[]] Detail errors
   */
  constructor(code?: string | number, message?: string, details = []) {
    if (typeof (code) === 'number') {
      this._code = code.toString();
    } else {
      this._code = code;
    }
    this._message = message;
    this._details = details;
  }

  /**
   * エラーコードを取得します。
   * @return {string} エラーコード
   */
  public get code(): string | undefined {
    return this._code;
  }

  /**
   * エラーコードを設定します。
   * @param {string} value エラーコード
   */
  public set code(value: string | undefined) {
    this._code = value;
  }

  /**
   * エラーメッセージを取得します。
   * @return {string} エラーメッセージ
   */
  public get message(): string | undefined {
    return this._message;
  }

  /**
   * エラーメッセージを設定します。
   * @param {string} value エラーメッセージ
   */
  public set message(value: string | undefined) {
    this._message = value;
  }

  /**
   * 詳細エラー（クライアント）を取得します。
   * @return {AwagError[]} 詳細エラー（クライアント）
   */
  public get details(): AwagError[] {
    return this._details;
  }

  /**
   * 詳細エラー（クライアント）を設定します。
   * @param {AwagError[]} value 詳細エラー（クライアント）
   */
  public set details(value: AwagError[]) {
    this._details = value;
  }

  /**
   * 詳細エラー（サーバエラー）を取得します。
   * @return {AwagError[]} 詳細エラー（サーバエラー）
   */
  public get errors(): AwagError[] | undefined {
    return this._errors;
  }

  /**
   * 詳細エラー（サーバエラー）を設定します。
   * @param {AwagError[]} value 詳細エラー（サーバエラー）
   */
  public set errors(value: AwagError[] | undefined) {
    this._errors = value;
  }

  /**
   * @description
   * クライアント処理で発生した詳細エラー情報を設定します。
   * @param code - 詳細コード
   * @param message - 詳細メッセージ
   */
  public pushDetail(code?: string | number, message?: string) {
    this._details.push(new AwagError(code, message));
  }

}
