/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';


const appRoutes: Routes = [
  { path: '', redirectTo: 'creditcode', pathMatch: 'full' },
  { path: 'creditcode', loadComponent: () => import('./creditcode-creditcode/creditcode-creditcode-custom.component').then(m => m.CreditcodeCreditcodeCustomComponent) },
];

@NgModule({
  imports: [
    RouterModule.forChild(appRoutes),
  ]
})
export class CreditcodeModule { }
