/* Generated by AWAG */
import { Component } from '@angular/core';

import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { MaintenanceLandComponent } from './maintenance-land.component';

/**
 * @description
 * Screen custom component
 * メニュー：Maintenance (お客様情報メンテ)
 * 画面：Land (陸事選択)
 * @extends {MaintenanceLandComponent}
 */
@Component({
  selector: 'app-maintenance-land',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './maintenance-land.component.html',
  styleUrls: ['../../common/app-common.scss', './maintenance-land-custom.component.scss'],
  providers: MaintenanceLandComponent.providers
})
export class MaintenanceLandCustomComponent extends MaintenanceLandComponent {

  /**
   * @description
   * Pre API call logic for awagInit (初期処理)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagInitPreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for awagInit (初期処理)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override awagInitSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for awagInit (初期処理)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagInitErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/
}
