/* [LOCKED] Generated by AWAG */
import { AfterViewInit, Component, inject } from '@angular/core';
import { AppBase } from './app-base'
import { AwagSharedModule } from './awag/awag-shared.module';
import { AppGuardService } from './app.guard';

@Component({
  selector: 'app-root',
  imports: [AwagSharedModule],
  templateUrl: './app.html',
  styleUrl: './app.scss'
})
export class App extends AppBase implements AfterViewInit {

  /** メニューガード */
  private readonly appGuard = inject(AppGuardService);

  // メニューガードの条件をカスタマイズ
  override ngAfterViewInit(): void {
    super.ngAfterViewInit();
    // 「メニュー階層表示」サンプルの同一階層メニューではダイアログ表示しない
    const excludedGuard = this.appGuard.getExcludedGuard();
    const customExcludedGuard = (currentUrl: string, nextUrl: string): boolean => {
      const pattern1 = currentUrl == '/menu3-1' && nextUrl == '/menu3-2';
      const pattern2 = currentUrl == '/menu3-2' && nextUrl == '/menu3-1';
      const pattern3 = currentUrl == '/menu1' && (nextUrl == '/menu2' || nextUrl == '/menu4');
      const pattern4 = currentUrl == '/menu2' && (nextUrl == '/menu1' || nextUrl == '/menu4');
      const pattern5 = currentUrl == '/menu4' && (nextUrl == '/menu1' || nextUrl == '/menu2');
      return excludedGuard(currentUrl, nextUrl) || pattern1 || pattern2 || pattern3 || pattern4 || pattern5;
    };
    this.appGuard.setExcludedGuard(customExcludedGuard);
  }

}