/* Generated by AWAG */
import { Component } from '@angular/core';

import { AwagConfirmModalComponent } from '../../../awag/modal/awag-confirm-modal.component';
import { ContactUpdateEmployeeModalComponent } from './contact-update-employee-modal.component';
import { AwagSharedModule } from '../../../awag/awag-shared.module';
import { AppCommonModule } from '../../../common/app-common.module';

@Component({
  selector: 'app-modal-base',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './contact-update-employee-modal.component.html'
})
export class ContactUpdateEmployeeModalCustomComponent extends ContactUpdateEmployeeModalComponent {

  /**
   * @description
   * 初期処理
   */
  override awagOnInit() {
    this.titleLabel = '社員情報選択';
    this.okButtonLabel = '選択';
    this.cancelButtonLabel = 'キャンセル';
  }

  /**
   * @description
   * モーダル表示中は追加、更新、削除ボタンを非表示にする
   */
  override awagAfterViewChecked() {
    // MDL, SIMPLE
    document.querySelector<HTMLInputElement>('#add')?.classList.add('awag-hidden');
    document.querySelector<HTMLInputElement>('#delete')?.classList.add('awag-hidden');
    document.querySelector<HTMLInputElement>('#update')?.classList.add('awag-hidden');
    // CARBON, MCW
    document.querySelector<HTMLInputElement>('#add')?.classList.add('awag--hidden');
    document.querySelector<HTMLInputElement>('#delete')?.classList.add('awag--hidden');
    document.querySelector<HTMLInputElement>('#update')?.classList.add('awag--hidden');
    // BS
    document.querySelector<HTMLInputElement>('#list-add')?.classList.add('d-none');
    document.querySelector<HTMLInputElement>('#list-delete')?.classList.add('d-none');
    document.querySelector<HTMLInputElement>('#list-update')?.classList.add('d-none');
  }

  /**
   * @description
   * OKボタンが押下された時の処理を記述します。
   * @param event 閉じるイベント情報
   * @returns モーダル表示を閉じる場合はtrue, 閉じない場合はfalseを応答します
   */
  protected override okButtonCustomLogic(event: any): boolean {
    let targetModel = null;
    if (this.router.url == '/contact/update/(modal:employee/search)' && this.awagContext.getNextModel()) {
      // 検索画面では選択されている社員情報を選択されたものとする
      targetModel = this.awagContext.getNextModel();
    }
    if (this.router.url == '/contact/update/(modal:employee/view)') {
      // 詳細画面では現在表示している社員情報を選択されたものとする
      targetModel = this.awagContext.getVModel('employee_view');
    }
    if (targetModel?.employeeno) {
      this.awagContext.getModalContext()!.getBaseModel().inchargeid = targetModel.employeeno;
      return true;
    } else {
      const modalRef = this.appCommon.getModal().open(AwagConfirmModalComponent, { centered: true, animation: false });
      modalRef.componentInstance.model = {
        body: this.translate.instant('custom.msg.E005'),
        showDismissButton: false,
        showCloseButton: true,
        closeButtonLabel: 'OK'
      };
      return false;
    }
  }

  /**
   * @description
   * キャンセルボタンが押下された時の処理を記述します。
   * @param event 閉じるイベント情報
   * @returns モーダル表示を閉じる場合はtrue, 閉じない場合はfalseを応答します
   *
  protected override cancelButtonCustomLogic(event: any): boolean {
    return true;
  }*/

  /**
   * @description
   * 閉じるアイコンがクリックされた時の処理を記述します。
   * @param event 閉じるイベント情報
   * @returns モーダル表示を閉じる場合はtrue, 閉じない場合はfalseを応答します
   *
  protected override closeIconCustomLogic(event: any): boolean {
    return true;
  }*/

}