/* Generated by AWAG */
import { Component } from '@angular/core';

import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { CustomecharacteristicCustomecharacteristicComponent } from './customecharacteristic-customecharacteristic.component';

/**
 * @description
 * Screen custom component
 * メニュー：Customecharacteristic (顧客特性登録)
 * 画面：Customecharacteristic (顧客特性登録)
 * @extends {CustomecharacteristicCustomecharacteristicComponent}
 */
@Component({
  selector: 'app-customecharacteristic-customecharacteristic',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './customecharacteristic-customecharacteristic.component.html',
  styleUrls: ['../../common/app-common.scss', './customecharacteristic-customecharacteristic-custom.component.scss'],
  providers: CustomecharacteristicCustomecharacteristicComponent.providers
})
export class CustomecharacteristicCustomecharacteristicCustomComponent extends CustomecharacteristicCustomecharacteristicComponent {
}
