/* Generated by AWAG */
import { Injectable } from '@angular/core';

import { MaintenanceLandTransportdeptOnChangeService } from './maintenance-land-transportdeptonchange.service';

/**
 * @description
 * API call service
 * 画面：Land (陸事選択)
 * イベント：TransportdeptOnChange (運輸局 onChange)
 * @extends {MaintenanceLandTransportdeptOnChangeService}
 */
@Injectable()
export class MaintenanceLandTransportdeptOnChangeCustomService extends MaintenanceLandTransportdeptOnChangeService {

  /**
   * @description
   * Execute API call.
   * @param {*} param API parameter
   * @returns {Observable<any>} Observable HTTP call
   *
  override execute(param: any): Observable<any> {
    return super.execute(param);
  }*/

}
