/* Generated by AWAG */
import { Component } from '@angular/core';

import { MaintenanceAttachmentsComponent } from './maintenance-attachments.component';
import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';

/**
 * @description
 * Screen custom component
 * メニュー：Maintenance (お客様情報メンテ)
 * 画面：Attachments (添付ファイル一覧)
 * @extends {MaintenanceAttachmentsComponent}
 */
@Component({
  selector: 'app-maintenance-attachments',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './maintenance-attachments.component.html',
  providers: MaintenanceAttachmentsComponent.providers
})
export class MaintenanceAttachmentsCustomComponent extends MaintenanceAttachmentsComponent {

  /**
   * @description
   * Custom logic for awagGoback (お客様詳細に戻る)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagGobackCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for listDownload (リストダウンロード(JSON形式))
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override listDownloadPreCallLogic(model: any) {
    // customize logic here
    return { customerid: model.customerid };
  }

  /**
   * @description
   * API success custom logic for listDownload (リストダウンロード(JSON形式))
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override listDownloadSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for listDownload (リストダウンロード(JSON形式))
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override listDownloadErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for awagInit (初期処理)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagInitPreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for awagInit (初期処理)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
   */
  protected override awagInitSuccessCustomLogic(res: any) {
    if (res.list === undefined) {
      res = { list: [] };
    }
    this.model = Object.assign(this.model, res); // Merge properties from res into this.model
	// 新規追加セクションの初期化
    this.model.attach = this.awagFilelist.files['attach'];
    this.model.attachExt = this.awagFilelist.files['attachExt'];
    if (this.awagFilelist.files['attach']) {
      this.awagFilelist.setPreview('preview', this.model.attach[0]);
    } else {
      this.model.comment = null;
    }
    if (this.awagFilelist.files['attachExt']) {
      this.awagFilelist.setPreview('previewExt', this.model.attachExt[0]);
    } else {
      this.model.commentExt = null;
    }
    return this.model;
  }

  /**
   * @description
   * API error custom logic for awagInit (初期処理)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagInitErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for listFilename (ファイル名)
   * @param {*} model Model data of screen
   * @param {number} index Index of selected row
   * @param {*} item Model data of selected item
   * @returns Edited model data of selected item
   *
  protected override listFilenamePreCallLogic(model: any, index: number, item: any) {
    // customize logic here
    return item;
  }*/

  /**
   * @description
   * API success custom logic for listFilename (ファイル名)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override listFilenameSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for listFilename (ファイル名)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override listFilenameErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for delete (削除)
   * @param {*} model Model data of screen
   * @param {number} index Index of selected row
   * @param {*} item Model data of selected item
   * @returns Edited model data of selected item
   *
  protected override deletePreCallLogic(model: any, index: number, item: any) {
    // customize logic here
    return item;
  }*/

  /**
   * @description
   * API success custom logic for delete (削除)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
   */
  protected override deleteSuccessCustomLogic(res: any) {
    this.awagInit();
    return this.model;
  }

  /**
   * @description
   * API error custom logic for delete (削除)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override deleteErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for addAttach (追加)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override addAttachPreCallLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * API success custom logic for addAttach (追加)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
   */
  protected override addAttachSuccessCustomLogic(res: any) {
    document.forms[0].reset();
    this.awagFilelist.clear();
    this.awagFilelist.removePreview('preview');
    this.awagFilelist.removePreview('previewExt');
    this.awagInit();
    this.model.comment = '';
    this.model.commentExt = '';
    return this.model;
  }

  /**
   * @description
   * API error custom logic for addAttach (追加)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   */
  protected override addAttachErrorCustomLogic(error: any, model: any) {
    // customize logic here
    this.model.attach = this.awagFilelist.files['attach'];
    this.model.attachExt = this.awagFilelist.files['attachExt'];
    return model;
  }

  /**
   * @description
   * Custom logic for confirmUpload (アップロード確認)
   * @param {*} model Model data of screen
   * @returns Edited model data
   */
  protected override confirmUploadCustomLogic(model: any) {
    if (this.model.attach) {
      this.awagFilelist.setFileList('attach', this.model.attach);
    }
    if (this.model.attachExt) {
      this.awagFilelist.setFileList('attachExt', this.model.attachExt);
    }
    return model;
  }

}
