/* Generated by AWAG */
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';


const appRoutes: Routes = [
  { path: '', redirectTo: 'basicattributes', pathMatch: 'full' },
  { path: 'basicattributes', loadComponent: () => import('./basicattributes-basicattributes/basicattributes-basicattributes-custom.component').then(m => m.BasicattributesBasicattributesCustomComponent) },
];

@NgModule({
  imports: [
    RouterModule.forChild(appRoutes),
  ]
})
export class BasicattributesModule { }
