/* Generated by AWAG */
import { AwagRoleBasedVisibilityConfig } from '../../awag/awag-visibility.service';

/**
 * @description
 * 画面の項目をロール別に活性表示・非活性表示・非表示制御を行うための設定です。
 */
export const ROLE_BASED_VISIBILITY: AwagRoleBasedVisibilityConfig = {
  '_group0': {
  },
  'list': {
  },
  '_group2': {
  },
  '_group3': {
  },
  'list1': {
  },
  '_group5': {
  },
  '_group6': {
  },
  'list2': {
  },
  'list3': {
  },
  'list4': {
  },
  'list5': {
  },
  'list6': {
  },
};
