/* Generated by AWAG */
import { Component } from '@angular/core';

import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { BasicattributesBasicattributesComponent } from './basicattributes-basicattributes.component';

/**
 * @description
 * Screen custom component
 * メニュー：Basicattributes (基本属性)
 * 画面：Basicattributes (基本属性)
 * @extends {BasicattributesBasicattributesComponent}
 */
@Component({
  selector: 'app-basicattributes-basicattributes',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './basicattributes-basicattributes.component.html',
  styleUrls: ['../../common/app-common.scss', './basicattributes-basicattributes-custom.component.scss'],
  providers: BasicattributesBasicattributesComponent.providers
})
export class BasicattributesBasicattributesCustomComponent extends BasicattributesBasicattributesComponent {

  /**
   * @description
   * Custom logic for dispatch2 (発信)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override dispatch2CustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for dispatch1 (発信)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override dispatch1CustomLogic(model: any) {
    // customize logic here
    return model;
  }*/
}
