/* Generated by AWAG */
import { AwagRoleBasedVisibilityConfig } from '../../awag/awag-visibility.service';

/**
 * @description
 * 画面の項目をロール別に活性表示・非活性表示・非表示制御を行うための設定です。
 */
export const ROLE_BASED_VISIBILITY: AwagRoleBasedVisibilityConfig = {
  '_group0': {
  },
  '_group1': {
  },
  '_group2': {
  },
  '_group3': {
  },
  '_group4': {
  },
  '_group5': {
  },
  '_group6': {
  },
  '_group7': {
  },
  '_group8': {
  },
  '_group9': {
  },
  '_group10': {
  },
  '_group11': {
  },
  'list': {
  },
};
