/* Generated by AWAG */
import { Component, inject } from '@angular/core';

import { AwagSharedModule } from '../../awag/awag-shared.module';
import { AppCommonModule } from '../../common/app-common.module';
import { MaintenanceSearchComponent } from './maintenance-search.component';
import { AwagFilelistService } from '../../awag/awag-file-list.service';

/**
 * @description
 * Screen custom component
 * メニュー：Maintenance (お客様情報メンテ)
 * 画面：Search (お客様検索)
 * @extends {MaintenanceSearchComponent}
 */
@Component({
  selector: 'app-maintenance-search',
  imports: [AppCommonModule, AwagSharedModule],
  templateUrl: './maintenance-search.component.html',
  styleUrls: ['../../common/app-common.scss', './maintenance-search-custom.component.scss'],
  providers: MaintenanceSearchComponent.providers
})
export class MaintenanceSearchCustomComponent extends MaintenanceSearchComponent {

  private readonly awagFileList = inject(AwagFilelistService);

  /**
   * @description
   * Pre API call logic for awagSearch (検索)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override awagSearchPreCallLogic(model: any) {
    // customize logic here
    if (model.checkbox != this.approveOptsCode[1].value) {
      // SEARCH_TABLE checkbox control, Change the condition when the checkbox is not checked, default : 'model.checkbox = null';
      // model.checkbox = this.approveOptsCode[0].value;
    }
    return model;
  }*/

  /**
   * @description
   * API success custom logic for awagSearch (検索)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   *
  protected override awagSearchSuccessCustomLogic(res: any) {
    // customize logic here
    return res;
  }*/

  /**
   * @description
   * API error custom logic for awagSearch (検索)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagSearchErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for view (詳細表示)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override viewCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Pre API call logic for awagSelect (選択)
   * @param {*} model Model data of screen
   * @param {number} index Index of selected row
   * @param {*} item Model data of selected item
   * @returns Edited model data of selected item
   *
  protected override awagSelectPreCallLogic(model: any, index: number, item: any) {
    // customize logic here
    return item;
  }*/

  /**
   * @description
   * API success custom logic for awagSelect (選択)
   * @param {*} res HTTP response
   * @returns Edited HTTP response
   */
  protected override awagSelectSuccessCustomLogic(res: any) {
    // customize logic here
    this.awagFileList.clear();
    return res;
  }

  /**
   * @description
   * API error custom logic for awagSelect (選択)
   * @param {*} error HTTP error response
   * @param {*} model Model data of screen
   *
  protected override awagSelectErrorCustomLogic(error: any, model: any) {
    // customize logic here
    return model;
  }*/

  /**
   * @description
   * Custom logic for update (更新)
   * @param {*} model Model data of screen
   * @returns Edited model data
   *
  protected override updateCustomLogic(model: any) {
    // customize logic here
    return model;
  }*/
}
