/* Generated by AWAG */
/**
 * ログレベルを定義したenumクラスです。
 */
export enum AWAG_LOGGER_LOGLEVEL {
  OFF = 0,
  FATAL = 100,
  ERROR = 200,
  WARN = 300,
  INFO = 400,
  DEBUG = 500,
  DEVELOP = 550,
  TRACE = 600,
  ALL = 700
}
