/* Generated by AWAG */

/**
 * @description
 * モーダル表示に関するコンテキスト情報を保持します
 */
export class AwagModalContext {

  /**
   * モーダルを起動した元画面のURL
   */
  private baseUrl: string | null = null;

  /**
   * モーダルを起動した元画面の画面モデル情報
   */
  private baseModel: any = null;

  /**
   * terminate時の処理
   */
  private terminateHandler: (() => void) | null = null;

  /**
   * @constructor
   * @param {string} baseUrl モーダルを起動した元画面のURL
   * @param {any} baseModel モーダルを起動した元画面の画面モデル情報
   */
  constructor(baseUrl: string, baseModel: any) {
    this.baseUrl = baseUrl;
    this.baseModel = baseModel;
  }

  /**
   * @description
   * @returns モーダルを起動した元画面のURL
   */
  getBaseUrl(): string | null {
    return this.baseUrl;
  }

  /**
   * @description
   * @param baseUrl モーダルを起動した元画面のURL
   */
  setBaseUrl(baseUrl: string | null) {
    this.baseUrl = baseUrl;
  }

  /**
   * @description
   * @returns モーダルを起動した元画面の画面モデル情報
   */
  getBaseModel(): any {
    return this.baseModel;
  }

  /**
   * @description
   * @param baseModel モーダルを起動した元画面の画面モデル情報
   */
  setBaseModel(baseModel: any) {
    this.baseModel = baseModel;
  }

  /**
   * terminate時の処理を登録します。
   * @param handler - terminate時の処理
   */
  set onTerminate(handler: () => void) {
    this.terminateHandler = handler;
  }

  /**
   * @description
   */
  terminate() {
    if (this.terminateHandler) {
      this.terminateHandler();
      this.terminateHandler = null;
    }
  }

}